export interface IDealList {
    ID: string | null,
    TITLE: string | null,
    TYPE_ID: string | null,
    STAGE_ID:string | null,
    PROBABILITY: string | null,
    CURRENCY_ID: string | null,
    OPPORTUNITY: string | null,
    IS_MANUAL_OPPORTUNITY: string | null,
    TAX_VALUE: string | null,
    LEAD_ID: string | null,
    COMPANY_ID: string | null,
    CONTACT_ID: string | null,
    QUOTE_ID: string | null,
    BEGINDATE: string | null,
    CLOSEDATE: string | null,
    ASSIGNED_BY_ID:string | null,
    CREATED_BY_ID:string | null,
    MODIFY_BY_ID: string | null,
    DATE_CREATE:string | null,
    DATE_MODIFY: string | null,
    OPENED: string | null,
    CLOSED: string | null,
    COMMENTS: string | null,
    ADDITIONAL_INFO: string | null,
    LOCATION_ID: string | null,
    CATEGORY_ID:string | null,
    STAGE_SEMANTIC_ID: string | null,
    IS_NEW: string | null,
    IS_RECURRING: string | null,
    IS_RETURN_CUSTOMER: string | null,
    IS_REPEATED_APPROACH: string | null,
    SOURCE_ID:string | null,
    SOURCE_DESCRIPTION: string | null,
    ORIGINATOR_ID: string | null,
    ORIGIN_ID: string | null,
    MOVED_BY_ID: 10
    MOVED_TIME: string | null,
    UTM_SOURCE:string | null,
    UTM_MEDIUM: string | null,
    UTM_CAMPAIGN: string | null,
    UTM_CONTENT:string | null,
    UTM_TERM: string | null,
}